#!/bin/sh
set -e

test "$1" != 'configure' || \
getent passwd gitdaemon >/dev/null || \
  adduser --system --home /nonexistent --no-create-home gitdaemon

# Automatically added by dh_installinit/11.5.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/git-daemon" ]; then
		update-rc.d git-daemon defaults >/dev/null
		invoke-rc.d git-daemon start || exit 1
	fi
fi
# End automatically added section

