#!/bin/sh
set -e
# Automatically added by dh_apache2/UNDECLARED
if true; then
	if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
		. /usr/share/apache2/apache2-maintscript-helper
		for conf in gitweb  ; do
			apache2_invoke enconf $conf  || exit 1
		done
	fi
fi
# End automatically added section
# Automatically added by dh_installdeb/11.5.4
dpkg-maintscript-helper mv_conffile /etc/apache2/conf.d/gitweb /etc/apache2/conf-available/gitweb.conf 1:2.1.4-2~ -- "$@"
# End automatically added section
