#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.5.4
dpkg-maintscript-helper mv_conffile /etc/apache2/conf.d/gitweb /etc/apache2/conf-available/gitweb.conf 1:2.1.4-2~ -- "$@"
# End automatically added section
